version: "0.1"
services:
  boudi:
    build: .
    networks:
      squasheeba:
        ipv4_address: 10.1.1.3
  pippin:
    build: .
    networks:
      squasheeba:
        ipv4_address: 10.1.1.2

networks:
  squasheeba:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
