version: "0.1"
services:
  boudi:
    build: .
    networks:
      squasheeba:
        ipv4_address: 10.1.1.3
      doggonet:
        ipv4_address: 10.1.2.3
    cap_add:
      - NET_ADMIN
  pippin:
    build: .
    networks:
      squasheeba:
        ipv4_address: 10.1.1.2
    cap_add:
      - NET_ADMIN

  tara:
    build: .
    networks:
      doggonet:
        ipv4_address: 10.1.2.2
    cap_add:
      - NET_ADMIN

networks:
  squasheeba:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
  doggonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
