version: "3.0"
services:
  boudi:
    build: .
    container_name: build-your-own-internet-002-boudi
    image: build-your-own-internet-002-boudi
    hostname: boudi
    networks:
      caternet:
        ipv4_address: 10.1.1.3
    cap_add:
      - NET_ADMIN
  pippin:
    build: .
    container_name: build-your-own-internet-002-pippin
    image: build-your-own-internet-002-pippin
    hostname: pippin
    networks:
      caternet:
        ipv4_address: 10.1.1.2
    cap_add:
      - NET_ADMIN

networks:
  caternet:
    name: build-your-own-internet-002-caternet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
