version: "3.0"
services:
  boudi:
    build: .
    hostname: boudi
    networks:
      squasheeba:
        ipv4_address: 10.1.1.3
    cap_add:
      - NET_ADMIN
  pippin:
    build: .
    hostname: pippin
    networks:
      squasheeba:
        ipv4_address: 10.1.1.2
    cap_add:
      - NET_ADMIN

networks:
  squasheeba:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
