---
- name: Setup test user with Git repo, PATH, Docker permissions, and SSH access
  hosts: localhost
  become: true
  vars:
    ansible_connection: local
    test_user_password: "{{ lookup('env', 'TEST_USER_PASSWORD') }}"
  tasks:
    - name: Ensure user 'test' exists with specified password
      user:
        name: test
        shell: /bin/bash
        create_home: yes
        password: "{{ test_user_password }}"

    - name: Add 'test' to 'docker' group
      user:
        name: test
        groups: docker
        append: yes

    - name: Clone Git repository into user's home directory
      git:
        repo: https://github.com/build-your-own-internet/byoi.git
        dest: /home/test/byoi
        version: recursive-dns
      become_user: test

    - name: Ensure '~/byoi/bin' is in user's PATH
      lineinfile:
        path: /home/test/.bashrc
        regexp: '^export PATH=.*byoi/bin'
        line: 'export PATH="$HOME/byoi/bin:$PATH"'
        state: present
        insertafter: EOF
      become_user: test

    - name: Change ownership of '/home/test/byoi' to user 'test'
      file:
        path: /home/test/byoi
        owner: test
        group: test
        recurse: yes

    - name: Create SSH configuration directory if it doesn't exist
      file:
        path: /etc/ssh/sshd_config.d
        state: directory
        mode: '0755'

    - name: Allow password authentication for 'test' user only
      copy:
        dest: /etc/ssh/sshd_config.d/70-allow-test-password.conf
        content: |
          Match User test
              PasswordAuthentication yes
      notify: Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted