version: "3.0"
services:
  client:
    build: .
    container_name: build-your-own-internet-001-client
    image: build-your-own-internet-001-client
    networks:
      network-1:
        ipv4_address: 10.1.1.3
    cap_add:
      - NET_ADMIN
  server:
    build: .
    container_name: build-your-own-internet-001-server
    image: build-your-own-internet-001-server
    networks:
      network-1:
        ipv4_address: 10.1.1.2
    cap_add:
      - NET_ADMIN

networks:
  network-1:
    name: build-your-own-internet-001-network-1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
