version: "3.0"
services:
  boudi:
    build: .
    hostname: boudi
    container_name: build-your-own-internet-traceroute-boudi
    image: build-your-own-internet-traceroute-boudi
    networks:
      caternet:
        ipv4_address: 10.1.1.3
      doggonet:
        ipv4_address: 10.1.2.3
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
  pippin:
    build: .
    hostname: pippin
    container_name: build-your-own-internet-traceroute-pippin
    image: build-your-own-internet-traceroute-pippin
    networks:
      caternet:
        ipv4_address: 10.1.1.2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=0

  tara:
    build: .
    hostname: tara
    container_name: build-your-own-internet-traceroute-tara
    image: build-your-own-internet-traceroute-tara
    networks:
      doggonet:
        ipv4_address: 10.1.2.2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=0

networks:
  caternet:
    name: build-your-own-internet-traceroute-caternet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24
  doggonet:
    name: build-your-own-internet-traceroute-doggonet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.2.0/24
